# Data Preprocessing

Importing Libraries

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [2]:
tf.__version__   ##Displays version of tensorflow we are using

'2.3.0'

In [3]:
dataset = pd.read_csv(r'data\Churn_Modelling.csv')
x= dataset.iloc[:,3:-1].values
y= dataset.iloc[:, -1].values
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

# Encoding Categorical data

Label Encoding Gender Column

In [4]:
from sklearn.preprocessing import LabelEncoder
Le = LabelEncoder()
x[:, 2] = Le.fit_transform(x[:, 2])
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


Onehotencoding for Geography column

In [5]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')  #Just change the column number which has to be transformed
x = np.array(ct.fit_transform(x))
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


# Split training and test set

In [6]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

# Feature Scaling

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train= sc.fit_transform(x_train)
x_test = sc.transform(x_test)

# Building ANN

Initializing ANN

In [8]:
ann = tf.keras.models.Sequential()   #Tensorflow 2.0 version has keras integrated. First call tensorflow and then keras library, models module and then sequential class

Adding input and first hidden layer

In [9]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))  # Because add is method, use braces to call dense class. relu - rectifier activation func

Adding second hidden layer

In [10]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu')) 

Adding output layer

In [11]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid')) #Number of units of ouput layer depends on output variable dimensions. Here as output is binary, we can take unit as 1

# Training ANN

Compiling ANN #with activation function and loss function i.e., optimiser and metric

In [12]:
ann.compile(optimizer='adam', loss = 'binary_crossentropy', metrics = ['accuracy']) #Mentioning optimizer, loss function, metrics

Training ANN on training set

In [13]:
ann.fit(x_train, y_train, batch_size=32, epochs= 100)

Epoch 1/100
250/250 [==============================] - 0s 885us/step - loss: 0.5450 - accuracy: 0.7763
Epoch 2/100
250/250 [==============================] - 0s 862us/step - loss: 0.4767 - accuracy: 0.7972
Epoch 3/100
250/250 [==============================] - 0s 870us/step - loss: 0.4532 - accuracy: 0.7972
Epoch 4/100
250/250 [==============================] - 0s 886us/step - loss: 0.4392 - accuracy: 0.7983
Epoch 5/100
250/250 [==============================] - 0s 806us/step - loss: 0.4307 - accuracy: 0.8085
Epoch 6/100
250/250 [==============================] - 0s 865us/step - loss: 0.4240 - accuracy: 0.8209
Epoch 7/100
250/250 [==============================] - 0s 802us/step - loss: 0.4192 - accuracy: 0.8255
Epoch 8/100
250/250 [==============================] - 0s 779us/step - loss: 0.4156 - accuracy: 0.8288
Epoch 9/100
250/250 [==============================] - 0s 782us/step - loss: 0.4128 - accuracy: 0.8311
Epoch 10/100
250/250 [==============================] - 0s 805us/step - l

250/250 [==============================] - 0s 906us/step - loss: 0.3843 - accuracy: 0.8440
Epoch 80/100
250/250 [==============================] - 0s 762us/step - loss: 0.3830 - accuracy: 0.8428
Epoch 81/100
250/250 [==============================] - 0s 799us/step - loss: 0.3815 - accuracy: 0.8450
Epoch 82/100
250/250 [==============================] - 0s 749us/step - loss: 0.3797 - accuracy: 0.8444
Epoch 83/100
250/250 [==============================] - 0s 820us/step - loss: 0.3774 - accuracy: 0.8466
Epoch 84/100
250/250 [==============================] - 0s 904us/step - loss: 0.3740 - accuracy: 0.8476
Epoch 85/100
250/250 [==============================] - 0s 814us/step - loss: 0.3702 - accuracy: 0.8490
Epoch 86/100
250/250 [==============================] - 0s 867us/step - loss: 0.3657 - accuracy: 0.8524
Epoch 87/100
250/250 [==============================] - 0s 854us/step - loss: 0.3606 - accuracy: 0.8525
Epoch 88/100
250/250 [==============================] - 0s 902us/step - loss:

# Making predictions and evaluating model

Predicting result of single observation

In [14]:
print(ann.predict(sc.transform([[1,0,0,600,1,40, 3, 60000, 2, 1, 1, 50000]])) > 0.5) #Any input of predict method must be 2-D array. Predict method has to be applied on same scale of training data. So here scale the required observation here using sc

#Since sigmoid is used as activation function in output layer, output is displayed in the form of probability. So here threshold of 0.5 is added to easily understand output

[[False]]


Predicting test set results

In [15]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
#np.set_printoptions(precision=2) #To display any numeric value only to two decimal places
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1)) # To display real results of test set and predicted profits of test set side by side.

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [1 0]]


Making Confusion matrix

In [16]:
from sklearn.metrics import confusion_matrix, accuracy_score
matrix = confusion_matrix(y_test, y_pred)
print(matrix)

[[1515   70]
 [ 219  196]]


In [17]:
accuracy_score(y_test, y_pred)

0.8555